# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='id',
        ),
        migrations.AlterField(
            model_name='map',
            name='map_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
