# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170721_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyData',
            fields=[
                ('quarter_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='')),
            ],
        ),
    ]
