# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_quarterlydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprocessingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
            ],
        ),
    ]
