# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_reprocessingdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReprocessingData',
        ),
    ]
