# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_reprocessingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorsData',
            fields=[
                ('quarter_operators_report', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='')),
            ],
        ),
    ]
