# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20171229_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorsdata',
            old_name='period',
            new_name='period_name',
        ),
    ]
