# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20171229_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaQuarterlyData',
            fields=[
                ('quarter_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='')),
            ],
        ),
    ]
